### ISSUE TITLE
Review 2: INSTALLATION

### ISSUE THREAD

**Issue by ltetrel** [harveyaa/nixtract-slurm#6]
INSTALLATION
1. /!\ Fix your versions in [requirements.txt](../blob/master/requirements.txt). If you don't, I can guarantee you 100% that you will have issues in the future when upstream packages updates.
2. nixtract (not nixtract-slurm) should be deployed on PyPi, that way it will be much "easier" for anyone to just install your software (and for any version).
3. nixtract install not working on computecanada
4. Overall I would suggest to create a Dockerfile if the installation is quite heavy (not necessarily the case here), and avoid the user to create a venv. It can also help if you require a specific python version, and should resolve the issue on computecanada.

**Comment by harveyaa** [comment]
I added versions to requirements.txt, nixtract is now on pypi, I tested the install on computecanada and it seems to work (at least for me). I'd like to avoid a docker file since the installation is quite lightweight. I'm going to mark this issue as closed, but I will open a new one as to configuring it so that the requirements are installed by pip automatically.
